name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  # Permette di far partire il sync manualmente dalla scheda Actions
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Sostituisci xmignax/JackVix con il nome corretto se diverso
          git push --force https://xmignax:$HF_TOKEN@huggingface.co/spaces/xmignax/JackVix main
